// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PollutionSensor.proto

package PollutionSensor;

public interface PollutionReadingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionSensor.PollutionReading)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double pollution_level = 1;</code>
   */
  double getPollutionLevel();

  /**
   * <code>string timestamp = 2;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
