// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PollutionSensor.proto

package PollutionSensor;

public interface PollutionHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionSensor.PollutionHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  java.util.List<PollutionSensor.PollutionReading> 
      getPollutionReadingsList();
  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  PollutionSensor.PollutionReading getPollutionReadings(int index);
  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  int getPollutionReadingsCount();
  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  java.util.List<? extends PollutionSensor.PollutionReadingOrBuilder> 
      getPollutionReadingsOrBuilderList();
  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  PollutionSensor.PollutionReadingOrBuilder getPollutionReadingsOrBuilder(
      int index);
}
