// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package base.weather;

/**
 * Protobuf type {@code Weather.WeatherForecastResponse}
 */
public  final class WeatherForecastResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Weather.WeatherForecastResponse)
    WeatherForecastResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeatherForecastResponse.newBuilder() to construct.
  private WeatherForecastResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeatherForecastResponse() {
    weatherReadings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WeatherForecastResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              weatherReadings_ = new java.util.ArrayList<base.weather.WeatherReading>();
              mutable_bitField0_ |= 0x00000001;
            }
            weatherReadings_.add(
                input.readMessage(base.weather.WeatherReading.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        weatherReadings_ = java.util.Collections.unmodifiableList(weatherReadings_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return base.weather.WeatherImpl.internal_static_Weather_WeatherForecastResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return base.weather.WeatherImpl.internal_static_Weather_WeatherForecastResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            base.weather.WeatherForecastResponse.class, base.weather.WeatherForecastResponse.Builder.class);
  }

  public static final int WEATHER_READINGS_FIELD_NUMBER = 1;
  private java.util.List<base.weather.WeatherReading> weatherReadings_;
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  public java.util.List<base.weather.WeatherReading> getWeatherReadingsList() {
    return weatherReadings_;
  }
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  public java.util.List<? extends base.weather.WeatherReadingOrBuilder> 
      getWeatherReadingsOrBuilderList() {
    return weatherReadings_;
  }
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  public int getWeatherReadingsCount() {
    return weatherReadings_.size();
  }
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  public base.weather.WeatherReading getWeatherReadings(int index) {
    return weatherReadings_.get(index);
  }
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  public base.weather.WeatherReadingOrBuilder getWeatherReadingsOrBuilder(
      int index) {
    return weatherReadings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < weatherReadings_.size(); i++) {
      output.writeMessage(1, weatherReadings_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < weatherReadings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, weatherReadings_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof base.weather.WeatherForecastResponse)) {
      return super.equals(obj);
    }
    base.weather.WeatherForecastResponse other = (base.weather.WeatherForecastResponse) obj;

    boolean result = true;
    result = result && getWeatherReadingsList()
        .equals(other.getWeatherReadingsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWeatherReadingsCount() > 0) {
      hash = (37 * hash) + WEATHER_READINGS_FIELD_NUMBER;
      hash = (53 * hash) + getWeatherReadingsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static base.weather.WeatherForecastResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static base.weather.WeatherForecastResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static base.weather.WeatherForecastResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static base.weather.WeatherForecastResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static base.weather.WeatherForecastResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static base.weather.WeatherForecastResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static base.weather.WeatherForecastResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static base.weather.WeatherForecastResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static base.weather.WeatherForecastResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static base.weather.WeatherForecastResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static base.weather.WeatherForecastResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static base.weather.WeatherForecastResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(base.weather.WeatherForecastResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Weather.WeatherForecastResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Weather.WeatherForecastResponse)
      base.weather.WeatherForecastResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return base.weather.WeatherImpl.internal_static_Weather_WeatherForecastResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return base.weather.WeatherImpl.internal_static_Weather_WeatherForecastResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              base.weather.WeatherForecastResponse.class, base.weather.WeatherForecastResponse.Builder.class);
    }

    // Construct using base.weather.WeatherForecastResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getWeatherReadingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (weatherReadingsBuilder_ == null) {
        weatherReadings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        weatherReadingsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return base.weather.WeatherImpl.internal_static_Weather_WeatherForecastResponse_descriptor;
    }

    @java.lang.Override
    public base.weather.WeatherForecastResponse getDefaultInstanceForType() {
      return base.weather.WeatherForecastResponse.getDefaultInstance();
    }

    @java.lang.Override
    public base.weather.WeatherForecastResponse build() {
      base.weather.WeatherForecastResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public base.weather.WeatherForecastResponse buildPartial() {
      base.weather.WeatherForecastResponse result = new base.weather.WeatherForecastResponse(this);
      int from_bitField0_ = bitField0_;
      if (weatherReadingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          weatherReadings_ = java.util.Collections.unmodifiableList(weatherReadings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.weatherReadings_ = weatherReadings_;
      } else {
        result.weatherReadings_ = weatherReadingsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof base.weather.WeatherForecastResponse) {
        return mergeFrom((base.weather.WeatherForecastResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(base.weather.WeatherForecastResponse other) {
      if (other == base.weather.WeatherForecastResponse.getDefaultInstance()) return this;
      if (weatherReadingsBuilder_ == null) {
        if (!other.weatherReadings_.isEmpty()) {
          if (weatherReadings_.isEmpty()) {
            weatherReadings_ = other.weatherReadings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWeatherReadingsIsMutable();
            weatherReadings_.addAll(other.weatherReadings_);
          }
          onChanged();
        }
      } else {
        if (!other.weatherReadings_.isEmpty()) {
          if (weatherReadingsBuilder_.isEmpty()) {
            weatherReadingsBuilder_.dispose();
            weatherReadingsBuilder_ = null;
            weatherReadings_ = other.weatherReadings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            weatherReadingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWeatherReadingsFieldBuilder() : null;
          } else {
            weatherReadingsBuilder_.addAllMessages(other.weatherReadings_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      base.weather.WeatherForecastResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (base.weather.WeatherForecastResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<base.weather.WeatherReading> weatherReadings_ =
      java.util.Collections.emptyList();
    private void ensureWeatherReadingsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        weatherReadings_ = new java.util.ArrayList<base.weather.WeatherReading>(weatherReadings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        base.weather.WeatherReading, base.weather.WeatherReading.Builder, base.weather.WeatherReadingOrBuilder> weatherReadingsBuilder_;

    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public java.util.List<base.weather.WeatherReading> getWeatherReadingsList() {
      if (weatherReadingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(weatherReadings_);
      } else {
        return weatherReadingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public int getWeatherReadingsCount() {
      if (weatherReadingsBuilder_ == null) {
        return weatherReadings_.size();
      } else {
        return weatherReadingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public base.weather.WeatherReading getWeatherReadings(int index) {
      if (weatherReadingsBuilder_ == null) {
        return weatherReadings_.get(index);
      } else {
        return weatherReadingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public Builder setWeatherReadings(
        int index, base.weather.WeatherReading value) {
      if (weatherReadingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWeatherReadingsIsMutable();
        weatherReadings_.set(index, value);
        onChanged();
      } else {
        weatherReadingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public Builder setWeatherReadings(
        int index, base.weather.WeatherReading.Builder builderForValue) {
      if (weatherReadingsBuilder_ == null) {
        ensureWeatherReadingsIsMutable();
        weatherReadings_.set(index, builderForValue.build());
        onChanged();
      } else {
        weatherReadingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public Builder addWeatherReadings(base.weather.WeatherReading value) {
      if (weatherReadingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWeatherReadingsIsMutable();
        weatherReadings_.add(value);
        onChanged();
      } else {
        weatherReadingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public Builder addWeatherReadings(
        int index, base.weather.WeatherReading value) {
      if (weatherReadingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWeatherReadingsIsMutable();
        weatherReadings_.add(index, value);
        onChanged();
      } else {
        weatherReadingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public Builder addWeatherReadings(
        base.weather.WeatherReading.Builder builderForValue) {
      if (weatherReadingsBuilder_ == null) {
        ensureWeatherReadingsIsMutable();
        weatherReadings_.add(builderForValue.build());
        onChanged();
      } else {
        weatherReadingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public Builder addWeatherReadings(
        int index, base.weather.WeatherReading.Builder builderForValue) {
      if (weatherReadingsBuilder_ == null) {
        ensureWeatherReadingsIsMutable();
        weatherReadings_.add(index, builderForValue.build());
        onChanged();
      } else {
        weatherReadingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public Builder addAllWeatherReadings(
        java.lang.Iterable<? extends base.weather.WeatherReading> values) {
      if (weatherReadingsBuilder_ == null) {
        ensureWeatherReadingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, weatherReadings_);
        onChanged();
      } else {
        weatherReadingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public Builder clearWeatherReadings() {
      if (weatherReadingsBuilder_ == null) {
        weatherReadings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        weatherReadingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public Builder removeWeatherReadings(int index) {
      if (weatherReadingsBuilder_ == null) {
        ensureWeatherReadingsIsMutable();
        weatherReadings_.remove(index);
        onChanged();
      } else {
        weatherReadingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public base.weather.WeatherReading.Builder getWeatherReadingsBuilder(
        int index) {
      return getWeatherReadingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public base.weather.WeatherReadingOrBuilder getWeatherReadingsOrBuilder(
        int index) {
      if (weatherReadingsBuilder_ == null) {
        return weatherReadings_.get(index);  } else {
        return weatherReadingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public java.util.List<? extends base.weather.WeatherReadingOrBuilder> 
         getWeatherReadingsOrBuilderList() {
      if (weatherReadingsBuilder_ != null) {
        return weatherReadingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(weatherReadings_);
      }
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public base.weather.WeatherReading.Builder addWeatherReadingsBuilder() {
      return getWeatherReadingsFieldBuilder().addBuilder(
          base.weather.WeatherReading.getDefaultInstance());
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public base.weather.WeatherReading.Builder addWeatherReadingsBuilder(
        int index) {
      return getWeatherReadingsFieldBuilder().addBuilder(
          index, base.weather.WeatherReading.getDefaultInstance());
    }
    /**
     * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
     */
    public java.util.List<base.weather.WeatherReading.Builder> 
         getWeatherReadingsBuilderList() {
      return getWeatherReadingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        base.weather.WeatherReading, base.weather.WeatherReading.Builder, base.weather.WeatherReadingOrBuilder> 
        getWeatherReadingsFieldBuilder() {
      if (weatherReadingsBuilder_ == null) {
        weatherReadingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            base.weather.WeatherReading, base.weather.WeatherReading.Builder, base.weather.WeatherReadingOrBuilder>(
                weatherReadings_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        weatherReadings_ = null;
      }
      return weatherReadingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Weather.WeatherForecastResponse)
  }

  // @@protoc_insertion_point(class_scope:Weather.WeatherForecastResponse)
  private static final base.weather.WeatherForecastResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new base.weather.WeatherForecastResponse();
  }

  public static base.weather.WeatherForecastResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeatherForecastResponse>
      PARSER = new com.google.protobuf.AbstractParser<WeatherForecastResponse>() {
    @java.lang.Override
    public WeatherForecastResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WeatherForecastResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WeatherForecastResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeatherForecastResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public base.weather.WeatherForecastResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

