// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package base.weather;

public interface WeatherForecastResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Weather.WeatherForecastResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  java.util.List<base.weather.WeatherReading> 
      getWeatherReadingsList();
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  base.weather.WeatherReading getWeatherReadings(int index);
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  int getWeatherReadingsCount();
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  java.util.List<? extends base.weather.WeatherReadingOrBuilder> 
      getWeatherReadingsOrBuilderList();
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  base.weather.WeatherReadingOrBuilder getWeatherReadingsOrBuilder(
      int index);
}
