// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package base.weather;

public interface WeatherForecastResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Weather.WeatherForecastResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitude = 1;</code>
   */
  double getLatitude();

  /**
   * <code>double longitude = 2;</code>
   */
  double getLongitude();

  /**
   * <code>double temperature = 3;</code>
   */
  double getTemperature();

  /**
   * <code>double humidity = 4;</code>
   */
  double getHumidity();

  /**
   * <code>double wind_speed = 5;</code>
   */
  double getWindSpeed();

  /**
   * <code>double precipitation = 6;</code>
   */
  double getPrecipitation();

  /**
   * <code>string timestamp = 7;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 7;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
