// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package base.weather;

public final class WeatherImpl {
  private WeatherImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Weather_WeatherForecastRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Weather_WeatherForecastRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Weather_WeatherForecastResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Weather_WeatherForecastResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rWeather.proto\022\007Weather\"=\n\026WeatherForec" +
      "astRequest\022\020\n\010latitude\030\001 \001(\001\022\021\n\tlongitud" +
      "e\030\002 \001(\001\"~\n\027WeatherForecastResponse\022\023\n\013te" +
      "mperature\030\001 \001(\001\022\020\n\010humidity\030\002 \001(\001\022\022\n\nwin" +
      "d_speed\030\003 \001(\001\022\025\n\rprecipitation\030\004 \001(\001\022\021\n\t" +
      "timestamp\030\005 \001(\t2d\n\007Weather\022Y\n\022GetWeather" +
      "Forecast\022\037.Weather.WeatherForecastReques" +
      "t\032 .Weather.WeatherForecastResponse\"\000B\035\n" +
      "\014base.weatherB\013WeatherImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Weather_WeatherForecastRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Weather_WeatherForecastRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Weather_WeatherForecastRequest_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_Weather_WeatherForecastResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Weather_WeatherForecastResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Weather_WeatherForecastResponse_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "WindSpeed", "Precipitation", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
