// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package base.login;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Login.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
