// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package base.login;

public final class LoginImpl {
  private LoginImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Login_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Login_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\022\005Login\"2\n\014LoginRequest\022\020\n\010" +
      "username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"@\n\rLogi" +
      "nResponse\022\017\n\007success\030\001 \001(\010\022\r\n\005token\030\002 \001(" +
      "\t\022\017\n\007message\030\003 \001(\t2=\n\005Login\0224\n\005Login\022\023.L" +
      "ogin.LoginRequest\032\024.Login.LoginResponse\"" +
      "\000B\031\n\nbase.loginB\tLoginImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Login_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Login_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_Login_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Login_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Login_LoginResponse_descriptor,
        new java.lang.String[] { "Success", "Token", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
