// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package base.weather;

public interface HumidityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Weather.HumidityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double humidity = 1;</code>
   */
  double getHumidity();
}
