// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package base.weather;

public interface WeatherReadingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Weather.WeatherReading)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();

  /**
   * <code>double humidity = 2;</code>
   */
  double getHumidity();

  /**
   * <code>double wind_speed = 3;</code>
   */
  double getWindSpeed();

  /**
   * <code>double precipitation = 4;</code>
   */
  double getPrecipitation();

  /**
   * <code>string timestamp = 5;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 5;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
