// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ControlPanel.proto

package base.controlPanel;

public final class ControlPanelImpl {
  private ControlPanelImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ControlPanel_DeviceStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ControlPanel_DeviceStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ControlPanel_DeviceStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ControlPanel_DeviceStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ControlPanel_DeviceIdentifier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ControlPanel_DeviceIdentifier_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ControlPanel_DeviceLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ControlPanel_DeviceLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ControlPanel.proto\022\014ControlPanel\"8\n\023De" +
      "viceStatusRequest\022\021\n\tdevice_id\030\001 \001(\t\022\016\n\006" +
      "status\030\002 \001(\010\"9\n\024DeviceStatusResponse\022\021\n\t" +
      "device_id\030\001 \001(\t\022\016\n\006status\030\002 \001(\010\"%\n\020Devic" +
      "eIdentifier\022\021\n\tdevice_id\030\001 \001(\t\"3\n\tDevice" +
      "Log\022\023\n\013log_message\030\001 \001(\t\022\021\n\ttimestamp\030\002 " +
      "\001(\t2\230\002\n\014ControlPanel\022Z\n\017SetDeviceStatus\022" +
      "!.ControlPanel.DeviceStatusRequest\032\".Con" +
      "trolPanel.DeviceStatusResponse\"\000\022Y\n\017GetD" +
      "eviceStatus\022\036.ControlPanel.DeviceIdentif" +
      "ier\032\".ControlPanel.DeviceStatusResponse\"" +
      "\000(\001\022Q\n\020StreamDeviceLogs\022\036.ControlPanel.D" +
      "eviceIdentifier\032\027.ControlPanel.DeviceLog" +
      "\"\000(\0010\001B\'\n\021base.controlPanelB\020ControlPane" +
      "lImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ControlPanel_DeviceStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ControlPanel_DeviceStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ControlPanel_DeviceStatusRequest_descriptor,
        new java.lang.String[] { "DeviceId", "Status", });
    internal_static_ControlPanel_DeviceStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ControlPanel_DeviceStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ControlPanel_DeviceStatusResponse_descriptor,
        new java.lang.String[] { "DeviceId", "Status", });
    internal_static_ControlPanel_DeviceIdentifier_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ControlPanel_DeviceIdentifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ControlPanel_DeviceIdentifier_descriptor,
        new java.lang.String[] { "DeviceId", });
    internal_static_ControlPanel_DeviceLog_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ControlPanel_DeviceLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ControlPanel_DeviceLog_descriptor,
        new java.lang.String[] { "LogMessage", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
