// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ControlPanel.proto

package track.controlPanel;

public interface DeviceStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ControlPanel.DeviceStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>bool status = 2;</code>
   */
  boolean getStatus();
}
