// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ControlPanel.proto

package track.controlPanel;

public interface DeviceIdentifierOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ControlPanel.DeviceIdentifier)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();
}
