// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ControlPanel.proto

package track.controlPanel;

public interface DeviceLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ControlPanel.DeviceLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string log_message = 1;</code>
   */
  java.lang.String getLogMessage();
  /**
   * <code>string log_message = 1;</code>
   */
  com.google.protobuf.ByteString
      getLogMessageBytes();

  /**
   * <code>string timestamp = 2;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
