// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PollutionSensor.proto

package base.pollutionSensor;

public final class PollutionSensorImpl {
  private PollutionSensorImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionSensor_PollutionLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionSensor_PollutionLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionSensor_PollutionReading_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionSensor_PollutionReading_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionSensor_PollutionHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionSensor_PollutionHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionSensor_PollutionHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionSensor_PollutionHistoryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025PollutionSensor.proto\022\017PollutionSensor" +
      "\"8\n\021PollutionLocation\022\020\n\010latitude\030\001 \001(\001\022" +
      "\021\n\tlongitude\030\002 \001(\001\">\n\020PollutionReading\022\027" +
      "\n\017pollution_level\030\001 \001(\001\022\021\n\ttimestamp\030\002 \001" +
      "(\t\"d\n\027PollutionHistoryRequest\022\020\n\010latitud" +
      "e\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\022\n\nstart_date" +
      "\030\003 \001(\t\022\020\n\010end_date\030\004 \001(\t\"Y\n\030PollutionHis" +
      "toryResponse\022=\n\022pollution_readings\030\001 \003(\013" +
      "2!.PollutionSensor.PollutionReading2\307\002\n\017" +
      "PollutionSensor\022\\\n\021GetPollutionLevel\022\".P" +
      "ollutionSensor.PollutionLocation\032!.Pollu" +
      "tionSensor.PollutionReading\"\000\022h\n\033Subscri" +
      "beToPollutionUpdates\022\".PollutionSensor.P" +
      "ollutionLocation\032!.PollutionSensor.Pollu" +
      "tionReading\"\0000\001\022l\n\023GetPollutionHistory\022(" +
      ".PollutionSensor.PollutionHistoryRequest" +
      "\032).PollutionSensor.PollutionHistoryRespo" +
      "nse\"\000B-\n\024base.pollutionSensorB\023Pollution" +
      "SensorImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PollutionSensor_PollutionLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PollutionSensor_PollutionLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionSensor_PollutionLocation_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_PollutionSensor_PollutionReading_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PollutionSensor_PollutionReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionSensor_PollutionReading_descriptor,
        new java.lang.String[] { "PollutionLevel", "Timestamp", });
    internal_static_PollutionSensor_PollutionHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PollutionSensor_PollutionHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionSensor_PollutionHistoryRequest_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "StartDate", "EndDate", });
    internal_static_PollutionSensor_PollutionHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PollutionSensor_PollutionHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionSensor_PollutionHistoryResponse_descriptor,
        new java.lang.String[] { "PollutionReadings", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
