// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package Weather;

public interface WeatherForecastResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Weather.WeatherForecastResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  java.util.List<Weather.WeatherReading> 
      getWeatherReadingsList();
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  Weather.WeatherReading getWeatherReadings(int index);
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  int getWeatherReadingsCount();
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  java.util.List<? extends Weather.WeatherReadingOrBuilder> 
      getWeatherReadingsOrBuilderList();
  /**
   * <code>repeated .Weather.WeatherReading weather_readings = 1;</code>
   */
  Weather.WeatherReadingOrBuilder getWeatherReadingsOrBuilder(
      int index);
}
