// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weather.proto

package track.weather;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Weather.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();
}
