// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PollutionSensor.proto

package track.pollutionSensor;

public interface PollutionHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionSensor.PollutionHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  java.util.List<track.pollutionSensor.PollutionReading> 
      getPollutionReadingsList();
  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  track.pollutionSensor.PollutionReading getPollutionReadings(int index);
  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  int getPollutionReadingsCount();
  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  java.util.List<? extends track.pollutionSensor.PollutionReadingOrBuilder> 
      getPollutionReadingsOrBuilderList();
  /**
   * <code>repeated .PollutionSensor.PollutionReading pollution_readings = 1;</code>
   */
  track.pollutionSensor.PollutionReadingOrBuilder getPollutionReadingsOrBuilder(
      int index);
}
