// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PollutionSensor.proto

package track.pollutionSensor;

public interface PollutionLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionSensor.PollutionLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitude = 1;</code>
   */
  double getLatitude();

  /**
   * <code>double longitude = 2;</code>
   */
  double getLongitude();
}
